# questions.py
# Structure:
# EEE_QUESTIONS: dict keyed by day-label → list of topics
#   each topic: { "topic": str, "mcq": [...5 MCQs...], "math": {...} }
# NON_DEPT_QUESTIONS: dict keyed by subject → list of topics
#   each topic: { "topic": str, "mcq": [...5 MCQs...] }

# MCQ format:
# { "q": question, "options": [A,B,C,D], "answer": 0-3 (index), "explanation": str }

# MATH format:
# { "q": question_text, "solution": solution_text }

EEE_QUESTIONS = {

# ══════════════════════════════════════════════════════════
# DAY 1 — Circuit Theory & Network Analysis
# ══════════════════════════════════════════════════════════
"Circuit Theory & Network Analysis": [

  { "topic": "KVL ও KCL — branch current method",
    "mcq": [
      {"q": "KVL অনুযায়ী একটি closed loop এ সকল voltage এর algebraic sum কত?",
       "options": ["অসীম","শূন্য","সর্বোচ্চ voltage এর সমান","সর্বনিম্ন voltage এর সমান"],
       "answer": 1, "explanation": "KVL: ΣV = 0 — Kirchhoff's Voltage Law"},
      {"q": "KCL অনুযায়ী একটি node এ প্রবেশকারী এবং বের হওয়া current এর সম্পর্ক কী?",
       "options": ["প্রবেশকারী > বের হওয়া","বের হওয়া > প্রবেশকারী","উভয় সমান","কোনো সম্পর্ক নেই"],
       "answer": 2, "explanation": "KCL: Σ(in) = Σ(out) — charge conservation"},
      {"q": "Branch current method কোন law এর উপর ভিত্তি করে কাজ করে?",
       "options": ["শুধু KVL","শুধু KCL","KVL ও KCL উভয়","Ohm's Law শুধু"],
       "answer": 2, "explanation": "Branch current method এ KVL ও KCL দুটোই ব্যবহার হয়"},
      {"q": "একটি circuit এ 3টি node থাকলে independent KCL equation কতটি লেখা যাবে?",
       "options": ["3","2","1","4"],
       "answer": 1, "explanation": "Independent KCL equations = nodes - 1 = 3-1 = 2"},
      {"q": "10Ω ও 20Ω series এ 30V source এ যুক্ত। 10Ω তে voltage কত?",
       "options": ["10V","20V","15V","30V"],
       "answer": 0, "explanation": "V = 30 × 10/(10+20) = 10V (voltage divider)"},
    ],
    "math": {"q": "নিচের circuit এ R1=4Ω, R2=6Ω, R3=12Ω সিরিজে V=44V। প্রতিটি রেজিস্টরে voltage drop ও current বের করো।",
             "solution": "মোট R = 4+6+12 = 22Ω\nI = V/R = 44/22 = 2A\nV_R1 = 2×4 = 8V\nV_R2 = 2×6 = 12V\nV_R3 = 2×12 = 24V\nCheck: 8+12+24 = 44V ✓"}
  },

  { "topic": "Mesh Analysis (matrix form সহ)",
    "mcq": [
      {"q": "Mesh Analysis এ mesh current কোন পথে ধরা হয়?",
       "options": ["যেকোনো দিকে","শুধু ঘড়ির কাঁটার দিকে","শুধু ঘড়ির বিপরীতে","loop এর বাইরে"],
       "answer": 0, "explanation": "Mesh current যেকোনো দিকে ধরা যায়, তবে সাধারণত clockwise ধরা হয়"},
      {"q": "Mesh Analysis প্রয়োগ করা যায় না কোন ধরনের circuit এ?",
       "options": ["Planar circuit","Non-planar circuit","Linear circuit","DC circuit"],
       "answer": 1, "explanation": "Mesh Analysis শুধুমাত্র planar (flat) circuit এ প্রযোজ্য"},
      {"q": "2টি mesh থাকলে mesh analysis এ কতটি equation পাওয়া যাবে?",
       "options": ["1","3","2","4"],
       "answer": 2, "explanation": "Mesh সংখ্যা = equation সংখ্যা"},
      {"q": "Supermesh তৈরি হয় কখন?",
       "options": ["Voltage source দুই mesh এর মাঝে থাকলে","Current source দুই mesh এর মাঝে থাকলে","Resistor দুই mesh এ থাকলে","কোনো source না থাকলে"],
       "answer": 1, "explanation": "Current source দুটি mesh এর shared branch এ থাকলে supermesh তৈরি হয়"},
      {"q": "Mesh equation এর matrix form [R][I] = [V] এ [R] matrix কেমন হয়?",
       "options": ["Asymmetric","Symmetric","Diagonal","Zero matrix"],
       "answer": 1, "explanation": "Mesh resistance matrix সবসময় symmetric হয়"},
    ],
    "math": {"q": "দুটি mesh: Mesh 1: 10V source, R1=2Ω (mesh 1 only), R3=4Ω (shared). Mesh 2: 6V source, R2=3Ω (mesh 2 only), R3=4Ω (shared)। I1 ও I2 বের করো।",
             "solution": "Mesh 1: (2+4)I1 - 4I2 = 10 → 6I1 - 4I2 = 10 ...(1)\nMesh 2: (3+4)I2 - 4I1 = 6 → -4I1 + 7I2 = 6 ...(2)\n(1)×7: 42I1 - 28I2 = 70\n(2)×4: -16I1 + 28I2 = 24\nযোগ: 26I1 = 94 → I1 = 3.615A\n(1) থেকে: I2 = (6×3.615-10)/4 = 2.923A"}
  },

  { "topic": "Nodal Analysis (supernode সহ)",
    "mcq": [
      {"q": "Nodal Analysis এ reference node কে কী বলা হয়?",
       "options": ["Active node","Ground node","Super node","Floating node"],
       "answer": 1, "explanation": "Reference node কে ground node বলে, voltage = 0V ধরা হয়"},
      {"q": "Supernode তৈরি হয় কখন?",
       "options": ["দুই node এর মাঝে resistor থাকলে","দুই node এর মাঝে voltage source থাকলে","দুই node এর মাঝে current source থাকলে","node এ short circuit থাকলে"],
       "answer": 1, "explanation": "দুটি non-reference node এর মাঝে voltage source থাকলে supernode তৈরি হয়"},
      {"q": "n টি node থাকলে independent nodal equation কতটি?",
       "options": ["n","n+1","n-1","2n"],
       "answer": 2, "explanation": "Independent equations = n-1 (reference node বাদ দিয়ে)"},
      {"q": "Nodal analysis এ প্রতিটি node এ কোন law apply করা হয়?",
       "options": ["KVL","KCL","Ohm's Law","Faraday's Law"],
       "answer": 1, "explanation": "প্রতিটি node এ KCL apply করা হয়"},
      {"q": "Nodal analysis এ অজানা রাশি কী?",
       "options": ["Branch current","Node voltage","Mesh current","Power"],
       "answer": 1, "explanation": "Nodal analysis এ node voltage বের করা হয়"},
    ],
    "math": {"q": "একটি circuit এ node V1 ও V2 আছে। Ground = 0V। Node V1 এ: 5A current source প্রবেশ করছে, V1 থেকে ground এ 2Ω, V1 থেকে V2 তে 4Ω। Node V2 তে: V2 থেকে ground এ 6Ω। V1 ও V2 বের করো।",
             "solution": "Node V1: 5 = V1/2 + (V1-V2)/4\n5 = 0.5V1 + 0.25V1 - 0.25V2\n5 = 0.75V1 - 0.25V2 ...(1)\nNode V2: (V1-V2)/4 = V2/6\n6(V1-V2) = 4V2\n6V1 = 10V2 → V1 = 5V2/3 ...(2)\n(2) → (1): 5 = 0.75×(5V2/3) - 0.25V2 = 1.25V2 - 0.25V2 = V2\nV2 = 5V, V1 = 25/3 ≈ 8.33V"}
  },

  { "topic": "Thevenin Theorem — step-by-step numerical",
    "mcq": [
      {"q": "Thevenin voltage (Vth) কীভাবে পরিমাপ করা হয়?",
       "options": ["Load short করে","Load open করে","Load সরিয়ে short circuit current মেপে","Source বন্ধ করে"],
       "answer": 1, "explanation": "Vth = open circuit voltage at the terminals"},
      {"q": "Thevenin resistance (Rth) বের করতে independent source গুলো কীভাবে বন্ধ করতে হয়?",
       "options": ["Voltage source open, current source short","Voltage source short, current source open","দুটোই short","দুটোই open"],
       "answer": 1, "explanation": "Voltage source → short circuit, Current source → open circuit"},
      {"q": "Maximum power transfer হয় যখন R_L = ?",
       "options": ["0","∞","Rth","2×Rth"],
       "answer": 2, "explanation": "Maximum power transfer theorem: R_L = Rth"},
      {"q": "Maximum power transfer এ efficiency কত?",
       "options": ["100%","75%","50%","25%"],
       "answer": 2, "explanation": "Max power transfer এ efficiency = 50% (বাকি 50% Rth তে নষ্ট)"},
      {"q": "Thevenin equivalent circuit এ কী থাকে?",
       "options": ["Current source + parallel resistance","Voltage source + series resistance","Current source + series resistance","Voltage source + parallel resistance"],
       "answer": 1, "explanation": "Thevenin = Vth (voltage source) + Rth (series resistance)"},
    ],
    "math": {"q": "একটি circuit এ V=24V, R1=6Ω, R2=3Ω, R3=4Ω। R1 ও V সিরিজে, R2 তাদের সাথে parallel, R3 হলো load। R3 এর জায়গায় Thevenin equivalent বের করো এবং R3 তে current নির্ণয় করো।",
             "solution": "Vth (R3 open): R1 ও R2 voltage divider\nVth = 24 × R2/(R1+R2) = 24 × 3/(6+3) = 8V\nRth (source short): R1 parallel R2 = (6×3)/(6+3) = 2Ω\nLoad current: I = Vth/(Rth+R3) = 8/(2+4) = 1.33A"}
  },

  { "topic": "Norton Theorem ও Thevenin↔Norton রূপান্তর",
    "mcq": [
      {"q": "Norton current (In) কীভাবে পাওয়া যায়?",
       "options": ["Terminal open করে voltage মেপে","Terminal short করে current মেপে","Load সংযুক্ত রেখে","Source বন্ধ করে"],
       "answer": 1, "explanation": "In = short circuit current at terminals"},
      {"q": "Norton equivalent circuit এ কী থাকে?",
       "options": ["Voltage source + series R","Current source + series R","Current source + parallel R","Voltage source + parallel R"],
       "answer": 2, "explanation": "Norton = In (current source) + Rn (parallel resistance)"},
      {"q": "Rn এবং Rth এর মধ্যে সম্পর্ক কী?",
       "options": ["Rn = 2×Rth","Rn = Rth/2","Rn = Rth","Rn = Rth²"],
       "answer": 2, "explanation": "Rn = Rth — একই পদ্ধতিতে বের করা হয়"},
      {"q": "Thevenin থেকে Norton রূপান্তরে In = ?",
       "options": ["Vth × Rth","Vth / Rth","Rth / Vth","Vth + Rth"],
       "answer": 1, "explanation": "In = Vth/Rth"},
      {"q": "Norton থেকে Thevenin রূপান্তরে Vth = ?",
       "options": ["In / Rn","In + Rn","In × Rn","In - Rn"],
       "answer": 2, "explanation": "Vth = In × Rn"},
    ],
    "math": {"q": "V=12V, R1=4Ω (series with V), R2=8Ω (parallel with terminals)। Norton equivalent বের করো।",
             "solution": "In (terminal short): R2 short হলে সব current R1 দিয়ে\nIn = 12/4 = 3A\nRn (source short): R1 ও R2 parallel\nRn = (4×8)/(4+8) = 32/12 = 2.67Ω\nVerify: Vth = In×Rn = 3×2.67 = 8V ✓"}
  },

  { "topic": "Superposition Theorem (multi-source circuit)",
    "mcq": [
      {"q": "Superposition theorem প্রযোজ্য কোন ধরনের circuit এ?",
       "options": ["Non-linear","Linear bilateral","Unilateral","যেকোনো"],
       "answer": 1, "explanation": "Superposition শুধুমাত্র linear bilateral circuit এ প্রযোজ্য"},
      {"q": "Superposition theorem এ dependent source কীভাবে ট্রিট করতে হয়?",
       "options": ["অন্য source এর মতো বন্ধ করতে হয়","সবসময় চালু রাখতে হয়","Open circuit করতে হয়","Short circuit করতে হয়"],
       "answer": 1, "explanation": "Dependent source কখনো বন্ধ করা যাবে না"},
      {"q": "Superposition দিয়ে সরাসরি কী বের করা যায় না?",
       "options": ["Voltage","Current","Power","উভয় voltage ও current"],
       "answer": 2, "explanation": "Power = I²R (nonlinear), তাই superposition সরাসরি power এ apply হয় না"},
      {"q": "একটি circuit এ 3টি independent source আছে। Superposition এ কতবার circuit solve করতে হবে?",
       "options": ["1","2","3","6"],
       "answer": 2, "explanation": "প্রতিটি source এর জন্য একবার করে = 3 বার"},
      {"q": "Superposition এ voltage source বন্ধ করা মানে?",
       "options": ["Open circuit","Short circuit","Remove করা","Reverse করা"],
       "answer": 1, "explanation": "Voltage source বন্ধ = short circuit (0V source)"},
    ],
    "math": {"q": "Circuit: V1=10V ও V2=5V দুটি source। R1=5Ω (V1 এর series), R2=10Ω (V2 এর series), R3=20Ω (দুটির মাঝে common)। R3 তে current বের করো Superposition দিয়ে।",
             "solution": "Step 1 (V1 চালু, V2 short):\nR2||R3 = (10×20)/(10+20) = 6.67Ω\nI_total = 10/(5+6.67) = 0.857A\nI3' = 0.857 × 10/(10+20) = 0.286A →\n\nStep 2 (V2 চালু, V1 short):\nR1||R3 = (5×20)/(5+20) = 4Ω\nI_total = 5/(10+4) = 0.357A\nI3'' = 0.357 × 5/(5+20) = 0.071A ←\n\nI3 = 0.286 - 0.071 = 0.215A →"}
  },

  { "topic": "Maximum Power Transfer — proof ও numerical",
    "mcq": [
      {"q": "Maximum power transfer theorem অনুযায়ী load এ সর্বোচ্চ power পাওয়া যায় যখন?",
       "options": ["RL = 0","RL = ∞","RL = Rth","RL = 2Rth"],
       "answer": 2, "explanation": "RL = Rth হলে maximum power transfer হয়"},
      {"q": "RL = Rth হলে maximum power Pmax = ?",
       "options": ["Vth²/Rth","Vth²/2Rth","Vth²/4Rth","Vth²/8Rth"],
       "answer": 2, "explanation": "Pmax = Vth²/(4Rth)"},
      {"q": "Maximum power transfer এ source থেকে মোট power এর কত % load এ যায়?",
       "options": ["25%","50%","75%","100%"],
       "answer": 1, "explanation": "50% load এ, 50% Rth তে dissipate হয়"},
      {"q": "Power engineering এ maximum power transfer preferred কেন নয়?",
       "options": ["Voltage কম হয়","50% efficiency অনেক কম","Current বেশি হয়","Frequency পরিবর্তন হয়"],
       "answer": 1, "explanation": "Power system এ 50% efficiency অগ্রহণযোগ্য; communication system এ ব্যবহার হয়"},
      {"q": "Vth=20V, Rth=5Ω হলে maximum power কত?",
       "options": ["20W","10W","5W","40W"],
       "answer": 0, "explanation": "Pmax = Vth²/4Rth = 400/20 = 20W"},
    ],
    "math": {"q": "Vth=100V, Rth=25Ω। (a) Maximum power কত? (b) RL=25Ω হলে power কত? (c) RL=50Ω হলে power কত?",
             "solution": "(a) Pmax = Vth²/4Rth = 10000/100 = 100W\n(b) RL=25Ω=Rth: I=100/(25+25)=2A, P=2²×25=100W ✓\n(c) RL=50Ω: I=100/(25+50)=1.33A, P=1.33²×50=88.9W < 100W"}
  },

  { "topic": "Star ↔ Delta Conversion",
    "mcq": [
      {"q": "Star থেকে Delta রূপান্তরে Delta এর প্রতিটি resistance কীভাবে বের করা হয়?",
       "options": ["Star R গুলোর গড়","প্রতিটি Star R এর বর্গ sum / opposite Star R","Star R গুলোর গুণফল","Star R গুলোর sum"],
       "answer": 1, "explanation": "R_ab = (Ra×Rb + Rb×Rc + Rc×Ra) / Rc"},
      {"q": "সমান তিনটি Star resistance R থেকে Delta resistance হবে?",
       "options": ["R/3","R","3R","R²"],
       "answer": 2, "explanation": "Symmetric: R_delta = 3 × R_star"},
      {"q": "Delta থেকে Star রূপান্তরে Star এর Ra = ?",
       "options": ["(Rab×Rca)/(Rab+Rbc+Rca)","Rab+Rbc+Rca","Rab×Rbc×Rca","(Rab+Rca)/Rbc"],
       "answer": 0, "explanation": "Ra = (Rab×Rca)/(Rab+Rbc+Rca)"},
      {"q": "সমান তিনটি Delta resistance R থেকে Star resistance হবে?",
       "options": ["3R","R","R/3","R²/3"],
       "answer": 2, "explanation": "Symmetric: R_star = R_delta/3"},
      {"q": "Star-Delta conversion কোন ধরনের circuit simplify করতে ব্যবহার হয়?",
       "options": ["Series circuit","Parallel circuit","Bridge circuit","Simple circuit"],
       "answer": 2, "explanation": "Wheatstone bridge ও তিন-ফেজ circuit এ Star-Delta conversion ব্যবহার হয়"},
    ],
    "math": {"q": "তিনটি Star resistance: Ra=10Ω, Rb=20Ω, Rc=30Ω। সমতুল্য Delta resistance R_ab, R_bc, R_ca বের করো।",
             "solution": "Sum of products = Ra×Rb + Rb×Rc + Rc×Ra\n= 10×20 + 20×30 + 30×10\n= 200 + 600 + 300 = 1100\n\nR_ab = 1100/Rc = 1100/30 = 36.67Ω\nR_bc = 1100/Ra = 1100/10 = 110Ω\nR_ca = 1100/Rb = 1100/20 = 55Ω"}
  },

  { "topic": "Wheatstone Bridge — balance condition ও galvanometer current",
    "mcq": [
      {"q": "Wheatstone bridge balance condition কী?",
       "options": ["P/Q = S/R","P×Q = R×S","P/R = Q/S","P+Q = R+S"],
       "answer": 0, "explanation": "Balance: P/Q = R/S অথবা PS = QR"},
      {"q": "Balanced Wheatstone bridge এ galvanometer দিয়ে কত current প্রবাহিত হয়?",
       "options": ["সর্বোচ্চ","সর্বনিম্ন","শূন্য","অসীম"],
       "answer": 2, "explanation": "Balanced bridge এ Ig = 0, উভয় midpoint voltage সমান"},
      {"q": "Wheatstone bridge কী পরিমাপ করতে ব্যবহার হয়?",
       "options": ["Voltage","Current","Resistance","Capacitance"],
       "answer": 2, "explanation": "Wheatstone bridge অজানা resistance নির্ভুলভাবে পরিমাপ করে"},
      {"q": "P=10Ω, Q=20Ω, R=30Ω হলে balance এর জন্য S = ?",
       "options": ["15Ω","60Ω","10Ω","40Ω"],
       "answer": 1, "explanation": "P/Q = R/S → S = QR/P = 20×30/10 = 60Ω"},
      {"q": "Unbalanced Wheatstone bridge এ galvanometer current বের করতে কোন theorem ব্যবহার করা হয়?",
       "options": ["Superposition","Thevenin","Norton","KVL শুধু"],
       "answer": 1, "explanation": "Thevenin theorem দিয়ে galvanometer current বের করা হয়"},
    ],
    "math": {"q": "Wheatstone bridge: P=100Ω, Q=200Ω, R=150Ω, S=350Ω, V=10V। Bridge balanced কিনা? না হলে galvanometer এ voltage কত? (Thevenin দিয়ে)",
             "solution": "Balance check: P/Q = 100/200 = 0.5, R/S = 150/350 = 0.429\n0.5 ≠ 0.429 → Unbalanced\n\nVth = V_BD = V×[R/(P+R) - S/(Q+S)]\n= 10×[150/250 - 350/550]\n= 10×[0.6 - 0.636]\n= 10×(-0.036) = -0.36V\n|V_galvanometer| = 0.36V"}
  },

  { "topic": "AC Circuit — Impedance, Reactance, Admittance",
    "mcq": [
      {"q": "Inductive reactance XL = ?",
       "options": ["1/ωL","ωL","ω/L","L/ω"],
       "answer": 1, "explanation": "XL = ωL = 2πfL (Ω)"},
      {"q": "Capacitive reactance XC = ?",
       "options": ["ωC","1/ωC","ω/C","C/ω"],
       "answer": 1, "explanation": "XC = 1/ωC = 1/2πfC (Ω)"},
      {"q": "Impedance Z = R + jX এ X > 0 হলে circuit কেমন?",
       "options": ["Capacitive","Resistive","Inductive","Resonant"],
       "answer": 2, "explanation": "X > 0 মানে inductive, X < 0 মানে capacitive"},
      {"q": "Admittance Y এবং Impedance Z এর মধ্যে সম্পর্ক?",
       "options": ["Y = Z","Y = Z²","Y = 1/Z","Y = Z/2"],
       "answer": 2, "explanation": "Y = 1/Z (Siemens)"},
      {"q": "f=50Hz, L=0.1H হলে XL কত?",
       "options": ["5Ω","31.4Ω","50Ω","0.1Ω"],
       "answer": 1, "explanation": "XL = 2π×50×0.1 = 31.4Ω"},
    ],
    "math": {"q": "Series RLC circuit: R=30Ω, L=0.2H, C=100μF, f=50Hz, V=200V। Z, I, power factor ও real power বের করো।",
             "solution": "XL = 2π×50×0.2 = 62.83Ω\nXC = 1/(2π×50×100×10⁻⁶) = 31.83Ω\nX = XL - XC = 62.83 - 31.83 = 31Ω\nZ = √(R²+X²) = √(900+961) = √1861 = 43.14Ω\nI = V/Z = 200/43.14 = 4.64A\nPF = cos φ = R/Z = 30/43.14 = 0.695 (lagging)\nP = VI×cosφ = 200×4.64×0.695 = 644.5W"}
  },

  { "topic": "Phasor diagram — series RLC",
    "mcq": [
      {"q": "Pure inductor এ voltage ও current এর মধ্যে phase difference কত?",
       "options": ["0°","90° (V leads I)","90° (I leads V)","180°"],
       "answer": 1, "explanation": "Inductor: V leads I by 90° (ELI)"},
      {"q": "Pure capacitor এ voltage ও current এর মধ্যে phase difference কত?",
       "options": ["0°","90° (V leads I)","90° (I leads V)","180°"],
       "answer": 2, "explanation": "Capacitor: I leads V by 90° (ICE)"},
      {"q": "ELI the ICE man — ELI মানে?",
       "options": ["Inductor এ E (voltage) leads I","Capacitor এ E leads I","Resistor এ E leads I","সবক্ষেত্রে E leads I"],
       "answer": 0, "explanation": "ELI: E(voltage) leads I in Inductor"},
      {"q": "Series RLC এ resonance এ phasor diagram এ net voltage কেমন?",
       "options": ["V_L + V_C","V_L - V_C = 0, net V = V_R","V_R + V_L","V_R - V_C"],
       "answer": 1, "explanation": "Resonance এ XL=XC, V_L ও V_C cancel, V = V_R"},
      {"q": "Lagging power factor মানে?",
       "options": ["Current leads voltage","Voltage leads current","In phase","কোনোটাই না"],
       "answer": 1, "explanation": "Lagging = inductive load, voltage leads current"},
    ],
    "math": {"q": "R=40Ω, XL=70Ω, XC=40Ω, V=250V। Phasor diagram আঁকার জন্য VR, VL, VC, phase angle ও Z বের করো।",
             "solution": "Z = R + j(XL-XC) = 40 + j30\n|Z| = √(40²+30²) = √(1600+900) = 50Ω\nI = 250/50 = 5A\nVR = IR = 5×40 = 200V (reference, 0°)\nVL = IXL = 5×70 = 350V (90° lead)\nVC = IXC = 5×40 = 200V (90° lag)\nNet reactive V = VL-VC = 150V\nφ = arctan(30/40) = 36.87° (lagging)\nCheck: V = √(VR²+(VL-VC)²) = √(200²+150²) = 250V ✓"}
  },

  { "topic": "Power Factor, Real/Reactive/Apparent Power",
    "mcq": [
      {"q": "Apparent power S এর unit কী?",
       "options": ["Watt","VAR","VA","kWh"],
       "answer": 2, "explanation": "Apparent power S = VA (Volt-Ampere)"},
      {"q": "Reactive power Q এর unit কী?",
       "options": ["Watt","VAR","VA","kWh"],
       "answer": 1, "explanation": "Reactive power Q = VAR (Volt-Ampere Reactive)"},
      {"q": "Power factor = ?",
       "options": ["P/Q","Q/S","P/S","S/P"],
       "answer": 2, "explanation": "PF = P/S = cosφ"},
      {"q": "Unity power factor এর ক্ষেত্রে Q = ?",
       "options": ["S","P","0","∞"],
       "answer": 2, "explanation": "PF=1 মানে φ=0°, Q = S×sinφ = 0"},
      {"q": "Power triangle এ S, P, Q এর সম্পর্ক?",
       "options": ["S = P + Q","S² = P² + Q²","P = S + Q","Q² = P² + S²"],
       "answer": 1, "explanation": "S² = P² + Q² (Pythagorean relation)"},
    ],
    "math": {"q": "একটি load এ V=230V, I=10A, PF=0.8 lagging। P, Q, S এবং φ বের করো।",
             "solution": "S = VI = 230×10 = 2300 VA = 2.3 kVA\nPF = cosφ = 0.8 → φ = 36.87°\nP = S×cosφ = 2300×0.8 = 1840 W = 1.84 kW\nQ = S×sinφ = 2300×0.6 = 1380 VAR = 1.38 kVAR\nCheck: S² = P²+Q² = 1840²+1380² = 3385600+1904400 = 5290000\n√5290000 = 2300 ✓"}
  },

  { "topic": "Resonance — series ও parallel (Q-factor, bandwidth)",
    "mcq": [
      {"q": "Series resonance এ impedance কেমন হয়?",
       "options": ["সর্বোচ্চ","সর্বনিম্ন (= R)","অসীম","শূন্য"],
       "answer": 1, "explanation": "Series resonance: Z = R (minimum), XL = XC cancel"},
      {"q": "Resonant frequency f0 = ?",
       "options": ["2π/√(LC)","1/(2π√(LC))","√(LC)/2π","2π√(LC)"],
       "answer": 1, "explanation": "f0 = 1/(2π√LC)"},
      {"q": "Q-factor (Quality factor) = ?",
       "options": ["R/XL","XL/R","R×XL","XL-R"],
       "answer": 1, "explanation": "Q = XL/R = ω0L/R (at resonance)"},
      {"q": "Bandwidth BW এবং Q এর সম্পর্ক?",
       "options": ["BW = Q×f0","BW = f0/Q","BW = f0×Q²","BW = Q/f0"],
       "answer": 1, "explanation": "BW = f0/Q"},
      {"q": "Parallel resonance এ impedance কেমন হয়?",
       "options": ["সর্বনিম্ন","সর্বোচ্চ","শূন্য","R এর সমান"],
       "answer": 1, "explanation": "Parallel resonance: Z সর্বোচ্চ (≈ L/CR)"},
    ],
    "math": {"q": "Series RLC: R=10Ω, L=0.1H, C=10μF। f0, Q-factor ও Bandwidth বের করো।",
             "solution": "f0 = 1/(2π√LC) = 1/(2π√(0.1×10×10⁻⁶))\n= 1/(2π×10⁻³) = 1000/2π = 159.15 Hz\n\nXL at f0 = 2π×159.15×0.1 = 100Ω\nQ = XL/R = 100/10 = 10\n\nBandwidth BW = f0/Q = 159.15/10 = 15.92 Hz\n\nf1 = f0 - BW/2 = 151.19 Hz (lower cutoff)\nf2 = f0 + BW/2 = 167.11 Hz (upper cutoff)"}
  },
],

# ══════════════════════════════════════════════════════════
# DAY 2 — Electronics
# ══════════════════════════════════════════════════════════
"Electronics — Devices & Circuits": [

  { "topic": "Diode — V-I characteristics, ideal vs practical",
    "mcq": [
      {"q": "Ideal diode এর forward voltage drop কত?",
       "options": ["0.3V","0.7V","0V","1V"],
       "answer": 2, "explanation": "Ideal diode: 0V drop (perfect switch)"},
      {"q": "Silicon diode এর practical forward voltage drop কত?",
       "options": ["0V","0.3V","0.7V","1.4V"],
       "answer": 2, "explanation": "Silicon diode: ~0.7V, Germanium: ~0.3V"},
      {"q": "Diode এর reverse breakdown voltage এর নিচে reverse current কেমন?",
       "options": ["বড়","শূন্য","অতি ক্ষুদ্র (leakage)","অসীম"],
       "answer": 2, "explanation": "Reverse bias এ খুব ক্ষুদ্র leakage current প্রবাহিত হয়"},
      {"q": "Diode এর V-I characteristics এ knee voltage মানে কী?",
       "options": ["Breakdown voltage","Forward conduction শুরু হওয়ার voltage","Reverse voltage","Peak voltage"],
       "answer": 1, "explanation": "Knee voltage = cut-in voltage, এর পর current দ্রুত বাড়ে"},
      {"q": "Zener diode সাধারণত কোন bias এ ব্যবহার হয়?",
       "options": ["Forward bias","Reverse bias","No bias","Both"],
       "answer": 1, "explanation": "Zener diode reverse bias এ voltage regulation এ ব্যবহার হয়"},
    ],
    "math": {"q": "একটি Silicon diode (Vf=0.7V) এর circuit এ V=10V, R=1kΩ series এ। Diode current ও R এ voltage বের করো।",
             "solution": "Diode forward biased (V > Vf)\nVR = V - Vf = 10 - 0.7 = 9.3V\nI = VR/R = 9.3/1000 = 9.3mA\nPower in diode = Vf×I = 0.7×9.3mA = 6.51mW"}
  },

  { "topic": "Half-wave Rectifier — Vdc, Idc, ripple factor",
    "mcq": [
      {"q": "Half-wave rectifier এর Vdc = ?",
       "options": ["Vm/π","2Vm/π","Vm/2","Vm/√2"],
       "answer": 0, "explanation": "Vdc = Vm/π ≈ 0.318Vm"},
      {"q": "Half-wave rectifier এর ripple factor কত?",
       "options": ["0.48","1.21","0.812","2.0"],
       "answer": 1, "explanation": "Ripple factor γ = 1.21 (121% — খুব বেশি)"},
      {"q": "Half-wave rectifier এর efficiency কত?",
       "options": ["81.2%","40.6%","50%","100%"],
       "answer": 1, "explanation": "Efficiency = 40.6%"},
      {"q": "Half-wave rectifier এ diode এর PIV (Peak Inverse Voltage) কত?",
       "options": ["Vm","2Vm","Vm/2","√2×Vm"],
       "answer": 0, "explanation": "Half-wave: PIV = Vm"},
      {"q": "Full-wave bridge rectifier এ Vdc = ?",
       "options": ["Vm/π","2Vm/π","Vm/2","Vm"],
       "answer": 1, "explanation": "Full-wave: Vdc = 2Vm/π ≈ 0.636Vm"},
    ],
    "math": {"q": "Half-wave rectifier এ transformer secondary Vrms=220V। Vm, Vdc, Idc (R_L=1kΩ) ও ripple voltage বের করো।",
             "solution": "Vm = Vrms×√2 = 220×1.414 = 311V\nVdc = Vm/π = 311/3.14 = 99V\nIdc = Vdc/RL = 99/1000 = 99mA\nVrms_out = Vm/2 = 155.5V\nRipple factor = 1.21\nRipple voltage = γ×Vdc = 1.21×99 = 119.8V"}
  },

  { "topic": "Full-wave Rectifier (bridge) — efficiency, PIV",
    "mcq": [
      {"q": "Bridge rectifier এ একসাথে কতটি diode conduct করে?",
       "options": ["1","2","3","4"],
       "answer": 1, "explanation": "Bridge: প্রতি half cycle এ 2টি diode conduct করে"},
      {"q": "Full-wave bridge rectifier এর PIV কত?",
       "options": ["Vm","2Vm","Vm/2","Vm-0.7"],
       "answer": 0, "explanation": "Bridge rectifier PIV = Vm (center-tap এ PIV = 2Vm)"},
      {"q": "Full-wave rectifier এর ripple factor কত?",
       "options": ["1.21","0.48","0.812","2.0"],
       "answer": 1, "explanation": "Full-wave ripple factor = 0.48"},
      {"q": "Full-wave rectifier এর efficiency কত?",
       "options": ["40.6%","81.2%","50%","100%"],
       "answer": 1, "explanation": "Full-wave efficiency = 81.2%"},
      {"q": "Bridge rectifier এ transformer secondary কতটি terminal লাগে?",
       "options": ["2","3","4","5"],
       "answer": 0, "explanation": "Bridge rectifier এ center-tap লাগে না, 2 terminal যথেষ্ট"},
    ],
    "math": {"q": "Full-wave bridge rectifier: Vrms=230V, RL=500Ω, প্রতি diode Vf=0.7V। Vm, Vdc, Idc ও efficiency বের করো।",
             "solution": "Vm = 230×√2 = 325.3V\nVdc = 2Vm/π - 2×Vf = 2×325.3/3.14 - 1.4 = 207.2 - 1.4 = 205.8V\nIdc = Vdc/RL = 205.8/500 = 411.6mA\nPdc = Vdc×Idc = 205.8×0.4116 = 84.7W\nPac = (Vm/√2)²/RL = (325.3/1.414)²/500 = 230²/500 = 105.8W\nEfficiency = Pdc/Pac = 84.7/105.8 = 80.1% ≈ 81.2%"}
  },

  { "topic": "BJT — CE/CB/CC configuration comparison",
    "mcq": [
      {"q": "BJT এর CE (Common Emitter) configuration এ কোন terminal common?",
       "options": ["Base","Collector","Emitter","কোনোটাই না"],
       "answer": 2, "explanation": "CE configuration এ Emitter input ও output উভয়ের common terminal"},
      {"q": "কোন BJT configuration এ current gain (β) সবচেয়ে বেশি?",
       "options": ["CB","CE","CC","সব সমান"],
       "answer": 1, "explanation": "CE: β = IC/IB (সবচেয়ে বেশি, typically 50-300)"},
      {"q": "CE configuration এ voltage gain কেমন?",
       "options": ["< 1","= 1","> 1 এবং phase inversion আছে","> 1 কিন্তু phase inversion নেই"],
       "answer": 2, "explanation": "CE: High voltage gain with 180° phase inversion"},
      {"q": "CC (Emitter Follower) configuration এর voltage gain কত?",
       "options": ["≈ 1",">> 1","< 1","0"],
       "answer": 0, "explanation": "CC: Voltage gain ≈ 1, high current gain, impedance matching এ ব্যবহার"},
      {"q": "CB configuration এর input impedance কেমন?",
       "options": ["সর্বোচ্চ","মাঝামাঝি","সর্বনিম্ন","অসীম"],
       "answer": 2, "explanation": "CB: সবচেয়ে কম input impedance (~20-50Ω)"},
    ],
    "math": {"q": "NPN BJT CE config: β=100, IB=40μA, VCC=12V, RC=2kΩ, VCE(sat)=0.2V। IC, VCE ও operating region নির্ণয় করো।",
             "solution": "IC = β×IB = 100×40μA = 4mA\nVCE = VCC - IC×RC = 12 - 4mA×2kΩ = 12 - 8 = 4V\nVCE > VCE(sat) = 0.2V → Active region এ আছে ✓\nPower dissipation: PC = VCE×IC = 4×4mA = 16mW"}
  },

  { "topic": "Op-Amp — inverting, non-inverting, gain calculation",
    "mcq": [
      {"q": "Ideal Op-Amp এর input impedance কত?",
       "options": ["0","50Ω","∞","1MΩ"],
       "answer": 2, "explanation": "Ideal Op-Amp: Zin = ∞"},
      {"q": "Inverting amplifier এর gain = ?",
       "options": ["Rf/R1","−Rf/R1","1 + Rf/R1","R1/Rf"],
       "answer": 1, "explanation": "Inverting: Av = −Rf/R1 (negative = phase inversion)"},
      {"q": "Non-inverting amplifier এর gain = ?",
       "options": ["Rf/R1","−Rf/R1","1 + Rf/R1","R1/Rf"],
       "answer": 2, "explanation": "Non-inverting: Av = 1 + Rf/R1"},
      {"q": "Voltage follower (unity gain buffer) এ gain কত?",
       "options": ["0","−1","+1","∞"],
       "answer": 2, "explanation": "Voltage follower: Rf=0, R1=∞, Av = 1"},
      {"q": "Ideal Op-Amp এর CMRR কত?",
       "options": ["0 dB","60 dB","∞","−∞"],
       "answer": 2, "explanation": "Ideal Op-Amp CMRR = ∞ (common mode signal সম্পূর্ণ reject করে)"},
    ],
    "math": {"q": "Inverting Op-Amp: R1=10kΩ, Rf=100kΩ, Vin=0.5V। Vout ও gain বের করো। Non-inverting হলে Vout কত হতো?",
             "solution": "Inverting:\nAv = −Rf/R1 = −100k/10k = −10\nVout = Av×Vin = −10×0.5 = −5V\n\nNon-inverting (same R values):\nAv = 1 + Rf/R1 = 1 + 10 = 11\nVout = 11×0.5 = +5.5V"}
  },
],

# ══════════════════════════════════════════════════════════
# DAY 3 — Power Engineering (abbreviated for space)
# ══════════════════════════════════════════════════════════
"Power Engineering": [

  { "topic": "Transformer — EMF equation, turns ratio",
    "mcq": [
      {"q": "Transformer এর EMF equation: E = ?",
       "options": ["4.44fNΦm","2.22fNΦm","fNΦm","8.88fNΦm"],
       "answer": 0, "explanation": "E = 4.44fNΦm (RMS value)"},
      {"q": "Step-up transformer এ N2/N1 = ?",
       "options": ["< 1","> 1","= 1","= 0"],
       "answer": 1, "explanation": "Step-up: N2 > N1, voltage বাড়ে"},
      {"q": "Ideal transformer এ V1/V2 = ?",
       "options": ["N2/N1","N1/N2","I1/I2","I2/I1"],
       "answer": 1, "explanation": "V1/V2 = N1/N2 (turns ratio)"},
      {"q": "Transformer শুধু AC তে কাজ করে কারণ?",
       "options": ["DC তে resistance বেশি","DC তে flux পরিবর্তন হয় না তাই EMF induce হয় না","AC তে efficiency বেশি","DC তে core saturate হয়"],
       "answer": 1, "explanation": "Faraday's law: e = -N×dφ/dt, DC তে dφ/dt = 0"},
      {"q": "Transformer এর kVA rating নির্ধারণ করে কে?",
       "options": ["Core loss","Copper loss","উভয়","Iron loss শুধু"],
       "answer": 2, "explanation": "kVA rating iron loss + copper loss উভয়ের উপর নির্ভরশীল"},
    ],
    "math": {"q": "50Hz transformer: Primary 230V, Secondary 46V, Primary turns N1=1000। N2, Φm (core area=50cm²) বের করো।",
             "solution": "Turns ratio = V1/V2 = 230/46 = 5\nN2 = N1/5 = 1000/5 = 200 turns\n\nEMF equation: E1 = 4.44×f×N1×Φm\n230 = 4.44×50×1000×Φm\nΦm = 230/(4.44×50×1000) = 1.036×10⁻³ Wb\n\nFlux density Bm = Φm/A = 1.036×10⁻³/(50×10⁻⁴) = 0.207 T"}
  },

  { "topic": "Transformer efficiency — condition for max efficiency",
    "mcq": [
      {"q": "Transformer এর maximum efficiency হয় যখন?",
       "options": ["Copper loss > Iron loss","Iron loss = Copper loss","Iron loss > Copper loss","No load"],
       "answer": 1, "explanation": "Max efficiency: Pi (iron) = Pc (copper)"},
      {"q": "Iron loss কোন test দিয়ে পরিমাপ করা হয়?",
       "options": ["Short circuit test","Open circuit test","Load test","Sumpner's test"],
       "answer": 1, "explanation": "OC test → Iron loss (core loss) পাওয়া যায়"},
      {"q": "Copper loss কোন test দিয়ে পরিমাপ করা হয়?",
       "options": ["Short circuit test","Open circuit test","Load test","Polarity test"],
       "answer": 0, "explanation": "SC test → Copper loss (I²R loss) পাওয়া যায়"},
      {"q": "Transformer efficiency η = ?",
       "options": ["Output/Input","(Output-Input)/Input","Input/Output","(Input-Loss)/Input"],
       "answer": 0, "explanation": "η = Output power/Input power = Pout/(Pout+Pi+Pc)"},
      {"q": "All-day efficiency বিবেচনা করা হয় কোন transformer এর জন্য?",
       "options": ["Power transformer","Distribution transformer","Welding transformer","Auto transformer"],
       "answer": 1, "explanation": "Distribution transformer 24 ঘন্টা energized থাকে, তাই all-day efficiency গুরুত্বপূর্ণ"},
    ],
    "math": {"q": "100kVA transformer: Iron loss=1kW, Full load copper loss=2kW, PF=0.8। Full load efficiency ও maximum efficiency এর load কত?",
             "solution": "Full load output = 100×0.8 = 80kW\nTotal loss = Pi + Pc = 1 + 2 = 3kW\nη_FL = 80/(80+3) = 80/83 = 96.4%\n\nMax efficiency এ: Pi = Pc(x)\n1 = x²×2 → x = √(1/2) = 0.707\nLoad at max η = 0.707×100 = 70.7 kVA\nOutput at max η = 70.7×0.8 = 56.57kW\nLoss at max η = 1+1 = 2kW\nη_max = 56.57/(56.57+2) = 96.6%"}
  },

  { "topic": "DC Motor — back EMF, torque equation, speed control",
    "mcq": [
      {"q": "DC motor এর back EMF Eb = ?",
       "options": ["V + IaRa","V - IaRa","IaRa","V × IaRa"],
       "answer": 1, "explanation": "Eb = V - IaRa (back EMF সবসময় applied voltage এর বিপরীত)"},
      {"q": "DC motor এর torque T ∝ ?",
       "options": ["φ/Ia","φ×Ia","Ia/φ","1/(φ×Ia)"],
       "answer": 1, "explanation": "T = kφIa, তাই T ∝ φ×Ia"},
      {"q": "DC shunt motor এর speed control কোন পদ্ধতিতে করা যায়?",
       "options": ["Armature resistance control","Field flux control","উভয়","কোনোটাই না"],
       "answer": 2, "explanation": "Shunt motor: armature resistance ও field current উভয় দিয়ে speed control"},
      {"q": "DC series motor এ no-load এ কী হয়?",
       "options": ["Speed সর্বনিম্ন","Speed অতিরিক্ত বেড়ে যায় (dangerous)","Speed স্থির থাকে","Motor বন্ধ হয়"],
       "answer": 1, "explanation": "Series motor: no-load এ speed ∞ → dangerous, তাই belt drive নিষিদ্ধ"},
      {"q": "DC motor এ mechanical power Pm = ?",
       "options": ["Eb×Ia","V×Ia","Ia²Ra","V×I"],
       "answer": 0, "explanation": "Pm = Eb×Ia (developed mechanical power)"},
    ],
    "math": {"q": "220V DC shunt motor: Ra=0.5Ω, Ia=20A, N=1000rpm। Back EMF, torque ও mechanical power বের করো।",
             "solution": "Eb = V - IaRa = 220 - 20×0.5 = 220 - 10 = 210V\nMechanical power: Pm = Eb×Ia = 210×20 = 4200W = 4.2kW\nTorque: T = Pm/ω = 4200/(2π×1000/60) = 4200/104.7 = 40.1 N·m"}
  },

  { "topic": "3-phase Induction Motor — rotating field, slip",
    "mcq": [
      {"q": "3-phase induction motor এ rotating magnetic field এর speed (Ns) = ?",
       "options": ["120f/P","60f/P","240f/P","f/P"],
       "answer": 0, "explanation": "Ns = 120f/P (synchronous speed, rpm)"},
      {"q": "Slip s = ?",
       "options": ["(N-Ns)/Ns","(Ns-N)/Ns","Ns/N","N/Ns"],
       "answer": 1, "explanation": "s = (Ns-N)/Ns"},
      {"q": "Full load এ slip সাধারণত কত?",
       "options": ["0%","1-5%","10-20%","50%"],
       "answer": 1, "explanation": "Induction motor full load slip ≈ 1-5%"},
      {"q": "Slip = 0 হলে motor কেমন?",
       "options": ["Stalled","Synchronous speed এ running","Overloaded","Off"],
       "answer": 1, "explanation": "s=0 মানে N=Ns (synchronous speed), কিন্তু induction motor এ practical এ হয় না"},
      {"q": "Rotor frequency fr = ?",
       "options": ["f","s×f","f/s","s/f"],
       "answer": 1, "explanation": "Rotor frequency fr = s×f (স্থির এ s=1, f_r=f; চলন্ত অবস্থায় কম)"},
    ],
    "math": {"q": "4-pole, 50Hz, 3-phase induction motor, full load speed=1440rpm। Synchronous speed, slip ও rotor frequency বের করো।",
             "solution": "Ns = 120f/P = 120×50/4 = 1500 rpm\nSlip s = (Ns-N)/Ns = (1500-1440)/1500 = 60/1500 = 0.04 = 4%\nRotor frequency fr = s×f = 0.04×50 = 2 Hz"}
  },
],

# ══════════════════════════════════════════════════════════
# DAY 4 — Signals & Control Systems
# ══════════════════════════════════════════════════════════
"Signals & Control Systems": [

  { "topic": "Laplace Transform — Transfer Function",
    "mcq": [
      {"q": "Laplace transform এ unit step function u(t) এর transform কী?",
       "options": ["1","1/s","1/s²","s"],
       "answer": 1, "explanation": "L{u(t)} = 1/s"},
      {"q": "Laplace transform এ δ(t) (impulse) এর transform কী?",
       "options": ["1/s","1","s","e⁻ˢ"],
       "answer": 1, "explanation": "L{δ(t)} = 1"},
      {"q": "Transfer function G(s) = ?",
       "options": ["Input/Output (Laplace)","Output/Input (Laplace)","Output×Input","Output-Input"],
       "answer": 1, "explanation": "G(s) = Y(s)/X(s) = Output/Input in Laplace domain"},
      {"q": "Pole কী?",
       "options": ["G(s) = 0 হওয়ার s এর মান","G(s) = ∞ হওয়ার s এর মান","G(s) = 1 হওয়ার s","Numerator এর roots"],
       "answer": 1, "explanation": "Pole: denominator = 0, G(s) → ∞"},
      {"q": "Final value theorem: lim(t→∞) f(t) = ?",
       "options": ["lim(s→∞) sF(s)","lim(s→0) sF(s)","lim(s→0) F(s)","lim(s→∞) F(s)"],
       "answer": 1, "explanation": "Final value theorem: lim(t→∞)f(t) = lim(s→0) sF(s)"},
    ],
    "math": {"q": "G(s) = 10/(s²+3s+2)। Poles, zeros বের করো ও unit step response এর steady-state value নির্ণয় করো।",
             "solution": "Poles: s²+3s+2 = 0 → (s+1)(s+2) = 0\nPoles: s = -1, s = -2 (both in left half plane → stable)\nZeros: numerator = 10 (constant) → no finite zeros\n\nUnit step: X(s) = 1/s\nY(s) = G(s)×(1/s) = 10/[s(s+1)(s+2)]\nSteady-state (Final Value Theorem):\ny(∞) = lim(s→0) s×Y(s) = lim(s→0) 10/[(s+1)(s+2)] = 10/(1×2) = 5"}
  },

  { "topic": "Control — Block Diagram, Mason's Rule, Stability",
    "mcq": [
      {"q": "Closed loop transfer function T(s) = ?",
       "options": ["G(s)","G(s)/[1+G(s)H(s)]","G(s)H(s)","1/[1+G(s)H(s)]"],
       "answer": 1, "explanation": "T(s) = G(s)/[1+G(s)H(s)] (negative feedback)"},
      {"q": "Routh-Hurwitz criterion দিয়ে কী নির্ধারণ করা হয়?",
       "options": ["Frequency response","System stability","Transient response","Steady state error"],
       "answer": 1, "explanation": "Routh-Hurwitz: সব poles left half plane এ আছে কিনা নির্ধারণ করে"},
      {"q": "Routh array এর প্রথম column এ কোনো sign change না থাকলে system কেমন?",
       "options": ["Unstable","Marginally stable","Stable","Oscillatory"],
       "answer": 2, "explanation": "No sign change in first column → all poles in LHP → stable"},
      {"q": "Type 0 system এ unit step এর steady-state error কত?",
       "options": ["0","1/(1+Kp)","1/Kv","∞"],
       "answer": 1, "explanation": "Type 0: ess = 1/(1+Kp), Kp = position error constant"},
      {"q": "Mason's gain formula এ forward path gain ও loop gain ব্যবহার করা হয়। Non-touching loop মানে?",
       "options": ["Loop যেগুলো common node শেয়ার করে","Loop যেগুলো কোনো common node শেয়ার করে না","সব loop","Feedback loop"],
       "answer": 1, "explanation": "Non-touching loops: কোনো shared node বা branch নেই"},
    ],
    "math": {"q": "G(s) = K/[s(s+2)(s+4)], H(s)=1। Routh-Hurwitz দিয়ে stability এর জন্য K এর range বের করো।",
             "solution": "Characteristic equation: 1 + G(s)H(s) = 0\ns(s+2)(s+4) + K = 0\ns³ + 6s² + 8s + K = 0\n\nRouth Array:\ns³ | 1    8\ns² | 6    K\ns¹ | (48-K)/6  0\ns⁰ | K\n\nFor stability, first column > 0:\n(48-K)/6 > 0 → K < 48\nK > 0\n\n∴ 0 < K < 48"}
  },
],

# ══════════════════════════════════════════════════════════
# DAY 5 — Digital Electronics & Microprocessor
# ══════════════════════════════════════════════════════════
"Digital Electronics & Microprocessor": [

  { "topic": "Number system — Binary, Octal, Hex, BCD conversion",
    "mcq": [
      {"q": "(1010)₂ = ?₁₀",
       "options": ["8","10","12","16"],
       "answer": 1, "explanation": "1×8+0×4+1×2+0×1 = 10"},
      {"q": "(255)₁₀ = ?₂",
       "options": ["11111110","11111111","11110000","10101010"],
       "answer": 1, "explanation": "255 = 128+64+32+16+8+4+2+1 = 11111111"},
      {"q": "(FF)₁₆ = ?₁₀",
       "options": ["240","255","256","250"],
       "answer": 1, "explanation": "F=15, FF = 15×16+15 = 255"},
      {"q": "BCD এ (9)₁₀ = ?",
       "options": ["1000","1001","1010","0111"],
       "answer": 1, "explanation": "BCD: 9 = 1001 (4-bit binary)"},
      {"q": "(101.11)₂ = ?₁₀",
       "options": ["5.5","5.75","5.25","6"],
       "answer": 1, "explanation": "4+1 = 5, .1×½+.1×¼ = 0.5+0.25 = 0.75, total = 5.75"},
    ],
    "math": {"q": "(173)₈ কে Binary ও Hexadecimal এ রূপান্তর করো। এবং (2C4)₁₆ কে Decimal এ রূপান্তর করো।",
             "solution": "(173)₈ → Binary:\n1=001, 7=111, 3=011\n(173)₈ = (001111011)₂ = (1111011)₂\n\n(1111011)₂ → Hex:\n0111 1011 = 7B\n(173)₈ = (7B)₁₆\n\n(2C4)₁₆ → Decimal:\n2×256 + 12×16 + 4×1\n= 512 + 192 + 4 = 708"}
  },

  { "topic": "Boolean Algebra & K-Map Simplification",
    "mcq": [
      {"q": "De Morgan's theorem: (A+B)' = ?",
       "options": ["A'+B'","A'B'","AB","A'×B"],
       "answer": 1, "explanation": "De Morgan: (A+B)' = A'·B'"},
      {"q": "Boolean expression: A+AB = ?",
       "options": ["AB","A+B","A","B"],
       "answer": 2, "explanation": "A+AB = A(1+B) = A×1 = A (absorption law)"},
      {"q": "K-map এ adjacent cell এর মধ্যে কতটি variable পরিবর্তন হয়?",
       "options": ["2","1","3","সব"],
       "answer": 1, "explanation": "K-map: adjacent cells differ by exactly 1 variable (Gray code)"},
      {"q": "4-variable K-map এ কতটি cell থাকে?",
       "options": ["8","16","32","4"],
       "answer": 1, "explanation": "4 variable → 2⁴ = 16 cells"},
      {"q": "K-map এ group size কত হতে পারে?",
       "options": ["যেকোনো","2 এর power (1,2,4,8,16...)","শুধু 4","শুধু 2"],
       "answer": 1, "explanation": "K-map group: 1, 2, 4, 8, 16 (power of 2)"},
    ],
    "math": {"q": "F(A,B,C) = Σm(1,3,5,7) — K-map দিয়ে simplify করো।",
             "solution": "Truth table:\nm1: ABC=001 → F=1\nm3: ABC=011 → F=1\nm5: ABC=101 → F=1\nm7: ABC=111 → F=1\n\nK-map (3 variable):\n    BC\nA  | 00 01 11 10\n0  |  0  1  1  0\n1  |  0  1  1  0\n\nGroup 1: m1,m3,m5,m7 (all C=1 cells) → simplified: C\n\nF = C\n\nVerification: F=1 only when C=1 ✓"}
  },

  { "topic": "Flip-Flop — SR, JK, D, T — truth table ও timing",
    "mcq": [
      {"q": "SR Flip-Flop এ S=1, R=1 হলে কী হয়?",
       "options": ["Q=1","Q=0","Q অপরিবর্তিত","Forbidden/Invalid state"],
       "answer": 3, "explanation": "SR FF: S=R=1 forbidden state (invalid/race condition)"},
      {"q": "JK Flip-Flop এ J=1, K=1 হলে output কী হয়?",
       "options": ["Q=1","Q=0","Q অপরিবর্তিত","Q toggles (complement)"],
       "answer": 3, "explanation": "JK: J=K=1 → Q toggles (JK FF SR এর forbidden state সমাধান করে)"},
      {"q": "D Flip-Flop এ clock edge এ Q = ?",
       "options": ["D'","D","J","K"],
       "answer": 1, "explanation": "D FF: Q(next) = D (data capture)"},
      {"q": "T Flip-Flop এ T=0 হলে?",
       "options": ["Toggle","Q=0","Q অপরিবর্তিত","Q=1"],
       "answer": 2, "explanation": "T FF: T=0 → No change, T=1 → Toggle"},
      {"q": "Master-Slave JK FF কোন সমস্যা দূর করে?",
       "options": ["Setup time","Race condition","Power consumption","Fan-out"],
       "answer": 1, "explanation": "Master-Slave JK FF race condition দূর করে"},
    ],
    "math": {"q": "একটি 3-bit binary ripple counter আঁকো এবং MOD কত তা নির্ণয় করো। কতটি FF লাগবে এবং output sequence কী?",
             "solution": "3-bit ripple counter:\n- 3টি JK FF লাগবে (J=K=1 always)\n- FF0 (LSB): clock থেকে trigger\n- FF1: FF0 এর Q থেকে trigger\n- FF2 (MSB): FF1 এর Q থেকে trigger\n\nMOD = 2³ = 8 (MOD-8 counter)\n\nSequence:\n000→001→010→011→100→101→110→111→000...\n(0→1→2→3→4→5→6→7→0...)"}
  },

  { "topic": "8085 architecture — registers, flags, buses",
    "mcq": [
      {"q": "8085 microprocessor এ address bus কত bit?",
       "options": ["8","16","32","64"],
       "answer": 1, "explanation": "8085: 16-bit address bus → 2¹⁶ = 64KB memory"},
      {"q": "8085 এর data bus কত bit?",
       "options": ["8","16","32","4"],
       "answer": 0, "explanation": "8085: 8-bit data bus (তাই 8085 নাম)"},
      {"q": "8085 এর accumulator কোনটি?",
       "options": ["B","C","A","H"],
       "answer": 2, "explanation": "Accumulator = A register (8-bit, arithmetic operations এ প্রধান)"},
      {"q": "8085 এ কতটি flag register আছে?",
       "options": ["3","5","8","16"],
       "answer": 1, "explanation": "8085: 5 flags — S, Z, AC, P, CY"},
      {"q": "8085 এ program counter (PC) কত bit?",
       "options": ["8","16","32","4"],
       "answer": 1, "explanation": "PC = 16-bit (next instruction address hold করে)"},
    ],
    "math": {"q": "8085 এ LXI H, 2050H instruction execute হলে H ও L register এ কী থাকবে? MOV A,M instruction এর পর A তে কী আসবে যদি memory 2050H তে 45H থাকে?",
             "solution": "LXI H, 2050H:\nH register = 20H\nL register = 50H\nHL pair = 2050H (memory address)\n\nMOV A,M:\nM = memory location pointed by HL = 2050H\nContent of 2050H = 45H\nA = 45H\n\nSo A register contains 45H = 69 (decimal)"}
  },
],

# ══════════════════════════════════════════════════════════
# DAY 6 — Electromagnetics & Communication
# ══════════════════════════════════════════════════════════
"Electromagnetics & Communication": [

  { "topic": "Electrostatics — Coulomb's Law, Gauss's Law",
    "mcq": [
      {"q": "Coulomb's Law: F = ?",
       "options": ["kQ1Q2/r","kQ1Q2/r²","kQ1Q2×r²","kQ1/Q2r²"],
       "answer": 1, "explanation": "F = kQ1Q2/r² = Q1Q2/(4πε₀r²)"},
      {"q": "Electric field E এর unit কী?",
       "options": ["V","V/m","C/m","N"],
       "answer": 1, "explanation": "E = V/m = N/C"},
      {"q": "Gauss's Law: ∮E·dA = ?",
       "options": ["Q/ε₀","ε₀/Q","Q×ε₀","0"],
       "answer": 0, "explanation": "Gauss: ∮E·dA = Q_enclosed/ε₀"},
      {"q": "Point charge Q থেকে r দূরত্বে electric field E = ?",
       "options": ["Q/4πε₀r","Q/4πε₀r²","Qr/4πε₀","4πε₀Q/r²"],
       "answer": 1, "explanation": "E = Q/(4πε₀r²) (radially outward)"},
      {"q": "Parallel plate capacitor এর capacitance C = ?",
       "options": ["εA/d","εd/A","ε/Ad","Ad/ε"],
       "answer": 0, "explanation": "C = ε₀εr×A/d"},
    ],
    "math": {"q": "দুটি point charge Q1=+4μC ও Q2=-2μC, 0.3m দূরত্বে। (a) Force কত ও কোন দিকে? (b) মধ্যবিন্দুতে E কত?",
             "solution": "(a) F = kQ1Q2/r² = 9×10⁹×4×10⁻⁶×2×10⁻⁶/0.09\n= 9×10⁹×8×10⁻¹²/0.09 = 0.8N\nAttractive (opposite charges)\n\n(b) At midpoint (r = 0.15m from each):\nE1 = kQ1/r² = 9×10⁹×4×10⁻⁶/0.0225 = 1.6MV/m (toward Q2)\nE2 = kQ2/r² = 9×10⁹×2×10⁻⁶/0.0225 = 0.8MV/m (toward Q2)\nE_total = E1+E2 = 2.4MV/m (toward Q2)"}
  },

  { "topic": "Faraday's Law — induced EMF, Lenz's law",
    "mcq": [
      {"q": "Faraday's Law: e = ?",
       "options": ["NΔΦ/Δt","-NdΦ/dt","NΦ","dB/dt"],
       "answer": 1, "explanation": "e = -N×dΦ/dt (negative sign = Lenz's law)"},
      {"q": "Lenz's law অনুযায়ী induced current কোন দিকে?",
       "options": ["Flux পরিবর্তনকে সহায়তা করে","Flux পরিবর্তনকে বাধা দেয়","Flux এর সাথে একই দিকে","Flux এর লম্বদিকে"],
       "answer": 1, "explanation": "Lenz's law: induced current এমন দিকে যায় যা flux পরিবর্তনকে oppose করে"},
      {"q": "একটি coil এ flux Φ = 0.5sin(100t) Wb, N=200। Peak EMF কত?",
       "options": ["50V","100V","10000V","200V"],
       "answer": 2, "explanation": "e = -N×dΦ/dt = -200×0.5×100×cos(100t), peak = 10000V"},
      {"q": "Self inductance L এর unit কী?",
       "options": ["Tesla","Weber","Henry","Farad"],
       "answer": 2, "explanation": "Inductance এর unit = Henry (H)"},
      {"q": "দুটি coil এর mutual inductance M = ?",
       "options": ["k√(L1L2)","k×(L1+L2)","L1×L2/k","k/(L1L2)"],
       "answer": 0, "explanation": "M = k√(L1L2), k = coupling coefficient (0 to 1)"},
    ],
    "math": {"q": "একটি 500-turn coil এ 0.1s এ flux 0.02Wb থেকে 0.06Wb এ পরিবর্তিত হয়। Induced EMF ও flux পরিবর্তনের হার বের করো।",
             "solution": "ΔΦ = 0.06 - 0.02 = 0.04 Wb\nΔt = 0.1s\ndΦ/dt = 0.04/0.1 = 0.4 Wb/s\n\nInduced EMF: e = N×dΦ/dt = 500×0.4 = 200V\n\nLenz's law অনুযায়ী এই EMF flux বৃদ্ধিকে oppose করবে।\nSelf inductance (if I changes 2A in 0.1s):\nL = e/(dI/dt) = 200/(2/0.1) = 200/20 = 10H"}
  },

  { "topic": "AM modulation — index, bandwidth, power",
    "mcq": [
      {"q": "AM modulation index m = ?",
       "options": ["Ac/Am","Am/Ac","Am×Ac","(Ac-Am)/Ac"],
       "answer": 1, "explanation": "m = Am/Ac (carrier amplitude দিয়ে message amplitude ভাগ)"},
      {"q": "AM এর bandwidth BW = ?",
       "options": ["fm","2fm","fc","fc±fm"],
       "answer": 1, "explanation": "AM BW = 2fm (upper ও lower sideband)"},
      {"q": "AM এ overmodulation হয় যখন?",
       "options": ["m < 1","m = 1","m > 1","m = 0"],
       "answer": 2, "explanation": "m > 1 → overmodulation → distortion"},
      {"q": "AM signal এর total power Pt = ?",
       "options": ["Pc(1+m²/2)","Pc×m²","Pc+Pm","Pc(1+m)"],
       "answer": 0, "explanation": "Pt = Pc(1 + m²/2)"},
      {"q": "FM এর Carson's rule অনুযায়ী bandwidth BW ≈ ?",
       "options": ["2fm","2Δf","2(Δf+fm)","Δf+fm"],
       "answer": 2, "explanation": "Carson's rule: BW = 2(Δf + fm) = 2fm(1+β)"},
    ],
    "math": {"q": "AM transmitter: Carrier power Pc=1000W, m=0.8। Total power, sideband power ও efficiency বের করো।",
             "solution": "Pt = Pc(1 + m²/2) = 1000×(1 + 0.64/2) = 1000×1.32 = 1320W\nSideband power = Pt - Pc = 1320 - 1000 = 320W\nEach sideband = 160W\n\nEfficiency = Sideband power/Total power\n= 320/1320 = 24.2%\n\n(Useful information is in sidebands, carrier has no information)"}
  },
],

# ══════════════════════════════════════════════════════════
# DAY 7 — DSP, Power Electronics & Revision
# ══════════════════════════════════════════════════════════
"DSP, Power Electronics & Revision": [

  { "topic": "Z-Transform — definition, ROC, properties",
    "mcq": [
      {"q": "Z-transform এ unit step u[n] এর Z-transform কী?",
       "options": ["z/(z-1)","1/(z-1)","z","1/z"],
       "answer": 0, "explanation": "Z{u[n]} = z/(z-1), ROC: |z|>1"},
      {"q": "Z-transform এ delay property: Z{x[n-k]} = ?",
       "options": ["z^k X(z)","z^(-k) X(z)","X(z)/k","kX(z)"],
       "answer": 1, "explanation": "Z{x[n-k]} = z⁻ᵏ X(z)"},
      {"q": "Sampling theorem অনুযায়ী sampling frequency fs ≥ ?",
       "options": ["fm","2fm","fm/2","4fm"],
       "answer": 1, "explanation": "Nyquist: fs ≥ 2fm (minimum sampling rate)"},
      {"q": "Aliasing ঘটে যখন?",
       "options": ["fs > 2fm","fs = 2fm","fs < 2fm","fs = fm"],
       "answer": 2, "explanation": "Aliasing: fs < 2fm (undersampling)"},
      {"q": "DFT এর N-point transform এ computational complexity কত?",
       "options": ["O(N)","O(N²)","O(NlogN)","O(logN)"],
       "answer": 1, "explanation": "DFT: O(N²), FFT: O(NlogN)"},
    ],
    "math": {"q": "x[n] = (0.5)ⁿ u[n] এর Z-transform ও ROC বের করো। এবং Nyquist rate বের করো যদি signal এর max frequency 4kHz হয়।",
             "solution": "Z{(0.5)ⁿ u[n]} = Σ(0.5z⁻¹)ⁿ (n=0 to ∞)\n= 1/(1-0.5z⁻¹) = z/(z-0.5)\nROC: |z| > 0.5\n\nNyquist rate = 2×fm = 2×4kHz = 8kHz\n∴ Minimum sampling frequency = 8000 samples/second\nSampling interval T = 1/8000 = 0.125ms"}
  },

  { "topic": "Power Electronics — SCR ও DC chopper",
    "mcq": [
      {"q": "SCR (Silicon Controlled Rectifier) কয়টি layer নিয়ে গঠিত?",
       "options": ["2","3","4","5"],
       "answer": 2, "explanation": "SCR: 4-layer PNPN device, 3 terminals (Anode, Cathode, Gate)"},
      {"q": "SCR turn-on করতে কী প্রয়োজন?",
       "options": ["শুধু forward voltage","Gate pulse + forward voltage","Reverse voltage","কোনো signal ছাড়াই"],
       "answer": 1, "explanation": "SCR: forward biased + gate trigger pulse দিলে turn-on হয়"},
      {"q": "DC chopper এ duty cycle D = ?",
       "options": ["Ton/T","Toff/T","T/Ton","Ton×T"],
       "answer": 0, "explanation": "D = Ton/T = Ton/(Ton+Toff)"},
      {"q": "Step-down chopper এ output voltage Vout = ?",
       "options": ["D×Vin","Vin/D","(1-D)×Vin","Vin/(1-D)"],
       "answer": 0, "explanation": "Buck (step-down) chopper: Vout = D×Vin"},
      {"q": "Step-up (boost) chopper এ Vout = ?",
       "options": ["D×Vin","Vin×(1-D)","Vin/(1-D)","Vin/D"],
       "answer": 2, "explanation": "Boost chopper: Vout = Vin/(1-D)"},
    ],
    "math": {"q": "DC Buck chopper: Vin=100V, D=0.6, RL=10Ω। Output voltage, current ও input current বের করো।",
             "solution": "Vout = D×Vin = 0.6×100 = 60V\nIout = Vout/RL = 60/10 = 6A\nPout = Vout×Iout = 60×6 = 360W\n\nAssuming ideal chopper (100% efficiency):\nPin = Pout = 360W\nIin(avg) = Pin/Vin = 360/100 = 3.6A\n\nVerify: Iin = D×Iout = 0.6×6 = 3.6A ✓"}
  },
],
}

# ══════════════════════════════════════════════════════════
# NON-DEPT MCQ QUESTIONS
# ══════════════════════════════════════════════════════════
NON_DEPT_QUESTIONS = {

"বাংলা ভাষা ও সাহিত্য": [
  {"topic": "সন্ধি",
   "mcq": [
     {"q": "'বিদ্যালয়' শব্দের সন্ধি বিচ্ছেদ কী?",
      "options": ["বিদ্যা+আলয়","বিদ্যা+লয়","বিদ্+আলয়","বিদ্যাল+য়"],
      "answer": 0, "explanation": "বিদ্যা+আলয় = বিদ্যালয় (স্বরসন্ধি)"},
     {"q": "স্বরসন্ধির নিয়ম অনুযায়ী অ+আ = ?",
      "options": ["অআ","আ","এ","ও"],
      "answer": 1, "explanation": "অ+আ = আ (স্বরসন্ধি: সমজাতীয় স্বর মিলে দীর্ঘ স্বর)"},
     {"q": "'মনোযোগ' শব্দের সন্ধি বিচ্ছেদ?",
      "options": ["মনো+যোগ","মন+যোগ","মনঃ+যোগ","মন+অযোগ"],
      "answer": 2, "explanation": "মনঃ+যোগ = মনোযোগ (বিসর্গ সন্ধি)"},
     {"q": "ব্যঞ্জনসন্ধির উদাহরণ কোনটি?",
      "options": ["বিদ্যালয়","মনোযোগ","দিগন্ত","নভোচর"],
      "answer": 2, "explanation": "দিক্+অন্ত = দিগন্ত (ব্যঞ্জনসন্ধি)"},
     {"q": "'উজ্জ্বল' শব্দটি কোন সন্ধির উদাহরণ?",
      "options": ["স্বরসন্ধি","ব্যঞ্জনসন্ধি","বিসর্গ সন্ধি","নিপাতনে সিদ্ধ"],
      "answer": 1, "explanation": "উৎ+জ্বল = উজ্জ্বল (ব্যঞ্জনসন্ধি)"},
   ]},
  {"topic": "বাংলা সাহিত্য",
   "mcq": [
     {"q": "রবীন্দ্রনাথ ঠাকুর নোবেল পুরস্কার পান কত সালে?",
      "options": ["1911","1913","1915","1921"],
      "answer": 1, "explanation": "১৯১৩ সালে গীতাঞ্জলি কাব্যগ্রন্থের জন্য নোবেল পান"},
     {"q": "কাজী নজরুল ইসলামের প্রথম কাব্যগ্রন্থ কোনটি?",
      "options": ["অগ্নিবীণা","বিষের বাঁশী","সঞ্চিতা","ছায়ানট"],
      "answer": 0, "explanation": "অগ্নিবীণা (১৯২২) — নজরুলের প্রথম কাব্যগ্রন্থ"},
     {"q": "বাংলা সাহিত্যের প্রথম মহিলা ঔপন্যাসিক কে?",
      "options": ["বেগম রোকেয়া","স্বর্ণকুমারী দেবী","কামিনী রায়","মহাশ্বেতা দেবী"],
      "answer": 1, "explanation": "স্বর্ণকুমারী দেবী — বাংলার প্রথম মহিলা ঔপন্যাসিক"},
     {"q": "'আমার সোনার বাংলা' কবিতাটি কে লিখেছেন?",
      "options": ["কাজী নজরুল","রবীন্দ্রনাথ ঠাকুর","জীবনানন্দ দাশ","মাইকেল মধুসূদন"],
      "answer": 1, "explanation": "রবীন্দ্রনাথ রচিত — বাংলাদেশের জাতীয় সংগীত"},
     {"q": "মধ্যযুগের বাংলা সাহিত্যের শ্রেষ্ঠ নিদর্শন কোনটি?",
      "options": ["চর্যাপদ","মনসামঙ্গল","শ্রীকৃষ্ণকীর্তন","পদ্মাবতী"],
      "answer": 2, "explanation": "শ্রীকৃষ্ণকীর্তন (বড়ু চণ্ডীদাস) — মধ্যযুগের অন্যতম শ্রেষ্ঠ কাব্য"},
   ]},
],

"English Language & Literature": [
  {"topic": "Grammar — Tense & Voice",
   "mcq": [
     {"q": "Choose the correct sentence:",
      "options": ["She don't like coffee","She doesn't likes coffee","She doesn't like coffee","She not like coffee"],
      "answer": 2, "explanation": "3rd person singular: doesn't + base verb"},
     {"q": "Passive voice of 'They built the bridge':",
      "options": ["The bridge built by them","The bridge was built by them","The bridge is built by them","The bridge were built by them"],
      "answer": 1, "explanation": "Simple past passive: was/were + past participle"},
     {"q": "'I wish I __ rich.' — correct form:",
      "options": ["am","was","were","will be"],
      "answer": 2, "explanation": "Subjunctive mood with 'wish': were (all persons)"},
     {"q": "Synonym of 'Benevolent':",
      "options": ["Cruel","Kind","Angry","Lazy"],
      "answer": 1, "explanation": "Benevolent = Kind, generous, charitable"},
     {"q": "Antonym of 'Verbose':",
      "options": ["Talkative","Wordy","Concise","Eloquent"],
      "answer": 2, "explanation": "Verbose = using too many words; Antonym = Concise"},
   ]},
],

"বাংলাদেশ বিষয়াবলি": [
  {"topic": "মুক্তিযুদ্ধ ও সংবিধান",
   "mcq": [
     {"q": "বাংলাদেশের স্বাধীনতার ঘোষণা কত তারিখে?",
      "options": ["২৫ মার্চ ১৯৭১","২৬ মার্চ ১৯৭১","১৬ ডিসেম্বর ১৯৭১","৭ মার্চ ১৯৭১"],
      "answer": 1, "explanation": "২৬ মার্চ ১৯৭১ — স্বাধীনতা দিবস"},
     {"q": "বাংলাদেশের সংবিধানের মূলনীতি কতটি?",
      "options": ["৩","৪","৫","৬"],
      "answer": 1, "explanation": "৪টি মূলনীতি: জাতীয়তাবাদ, সমাজতন্ত্র, গণতন্ত্র, ধর্মনিরপেক্ষতা"},
     {"q": "মুক্তিযুদ্ধে মোট কতটি সেক্টর ছিল?",
      "options": ["৯","১০","১১","১২"],
      "answer": 2, "explanation": "১১টি সেক্টর (পরে নৌ সেক্টর যোগ হয়)"},
     {"q": "বাংলাদেশের প্রথম রাষ্ট্রপতি কে?",
      "options": ["বঙ্গবন্ধু শেখ মুজিবুর রহমান","সৈয়দ নজরুল ইসলাম","তাজউদ্দীন আহমদ","এ এইচ এম কামারুজ্জামান"],
      "answer": 0, "explanation": "বঙ্গবন্ধু শেখ মুজিবুর রহমান — প্রথম রাষ্ট্রপতি"},
     {"q": "বাংলাদেশ সংবিধান কত তারিখে কার্যকর হয়?",
      "options": ["১৬ ডিসেম্বর ১৯৭১","৪ নভেম্বর ১৯৭২","১৬ ডিসেম্বর ১৯৭২","২৬ মার্চ ১৯৭৩"],
      "answer": 2, "explanation": "১৬ ডিসেম্বর ১৯৭২ — সংবিধান কার্যকর হয়"},
   ]},
],

"আন্তর্জাতিক বিষয়াবলি": [
  {"topic": "জাতিসংঘ ও আন্তর্জাতিক সংগঠন",
   "mcq": [
     {"q": "জাতিসংঘ প্রতিষ্ঠিত হয় কত সালে?",
      "options": ["1944","1945","1946","1950"],
      "answer": 1, "explanation": "UN প্রতিষ্ঠা: ২৪ অক্টোবর ১৯৪৫"},
     {"q": "জাতিসংঘের নিরাপত্তা পরিষদের স্থায়ী সদস্য কতটি?",
      "options": ["3","5","10","15"],
      "answer": 1, "explanation": "P5: USA, UK, France, Russia, China"},
     {"q": "IMF এর সদর দপ্তর কোথায়?",
      "options": ["New York","Geneva","Washington D.C.","London"],
      "answer": 2, "explanation": "IMF HQ: Washington D.C., USA"},
     {"q": "SAARC এর সদস্য দেশ কতটি?",
      "options": ["6","7","8","9"],
      "answer": 2, "explanation": "SAARC: ৮ সদস্য — বাংলাদেশ, ভারত, পাকিস্তান, শ্রীলংকা, নেপাল, ভুটান, মালদ্বীপ, আফগানিস্তান"},
     {"q": "UNESCO এর সদর দপ্তর কোথায়?",
      "options": ["New York","Paris","Geneva","Vienna"],
      "answer": 1, "explanation": "UNESCO HQ: Paris, France"},
   ]},
],

"সাধারণ বিজ্ঞান": [
  {"topic": "পদার্থবিজ্ঞান ও জীববিজ্ঞান",
   "mcq": [
     {"q": "আলোর গতি কত?",
      "options": ["3×10⁶ m/s","3×10⁸ m/s","3×10¹⁰ m/s","3×10⁴ m/s"],
      "answer": 1, "explanation": "c = 3×10⁸ m/s (vacuum এ)"},
     {"q": "মানবদেহের স্বাভাবিক তাপমাত্রা কত?",
      "options": ["36°C","37°C","38°C","98°F"],
      "answer": 1, "explanation": "37°C = 98.6°F — স্বাভাবিক দেহ তাপমাত্রা"},
     {"q": "DNA এর পূর্ণ রূপ কী?",
      "options": ["Deoxyribonucleic Acid","Deoxyribonitric Acid","Diribonucleic Acid","Deoxyribose Nucleic Acid"],
      "answer": 0, "explanation": "DNA = Deoxyribonucleic Acid"},
     {"q": "সালোকসংশ্লেষণে কোন গ্যাস ব্যবহার হয়?",
      "options": ["O₂","N₂","CO₂","H₂"],
      "answer": 2, "explanation": "Photosynthesis: 6CO₂+6H₂O → C₆H₁₂O₆+6O₂"},
     {"q": "বিদ্যুৎ পরিবাহিতার একক কী?",
      "options": ["Ohm","Ampere","Siemens","Volt"],
      "answer": 2, "explanation": "Conductance এর unit = Siemens (S) = 1/Ohm"},
   ]},
],

"কম্পিউটার ও তথ্যপ্রযুক্তি": [
  {"topic": "নেটওয়ার্ক ও হার্ডওয়্যার",
   "mcq": [
     {"q": "OSI model এ কতটি layer আছে?",
      "options": ["5","6","7","4"],
      "answer": 2, "explanation": "OSI: 7 layers — Physical, Data Link, Network, Transport, Session, Presentation, Application"},
     {"q": "IP address এর কতটি version ব্যাপকভাবে ব্যবহৃত হয়?",
      "options": ["1","2","3","2 (IPv4 ও IPv6)"],
      "answer": 3, "explanation": "IPv4 (32-bit) ও IPv6 (128-bit) — দুটোই ব্যবহৃত"},
     {"q": "1 GB = কত MB?",
      "options": ["100","1000","1024","512"],
      "answer": 2, "explanation": "1 GB = 1024 MB (binary system)"},
     {"q": "ROM এর পূর্ণ রূপ কী?",
      "options": ["Read Only Memory","Random Only Memory","Read Open Memory","Readable Output Memory"],
      "answer": 0, "explanation": "ROM = Read Only Memory (non-volatile)"},
     {"q": "HTTP এর port number কত?",
      "options": ["21","23","80","443"],
      "answer": 2, "explanation": "HTTP = port 80, HTTPS = port 443"},
   ]},
],

"গাণিতিক যুক্তি": [
  {"topic": "পাটিগণিত ও বীজগণিত",
   "mcq": [
     {"q": "১২ ও ১৮ এর ল.সা.গু কত?",
      "options": ["6","36","72","24"],
      "answer": 1, "explanation": "12=2²×3, 18=2×3², LCM=2²×3²=36"},
     {"q": "একটি সংখ্যার ৪০% = ৮০। সংখ্যাটি কত?",
      "options": ["160","200","180","220"],
      "answer": 1, "explanation": "x×40/100=80 → x=80×100/40=200"},
     {"q": "x²-5x+6=0 এর সমাধান কী?",
      "options": ["x=2,3","x=1,6","x=-2,-3","x=2,-3"],
      "answer": 0, "explanation": "(x-2)(x-3)=0 → x=2 or x=3"},
     {"q": "৫ জন শ্রমিক ৫ দিনে ৫টি কাজ করে। ১০ জন ১০ দিনে কতটি কাজ করবে?",
      "options": ["10","20","50","100"],
      "answer": 1, "explanation": "প্রতি জন প্রতি দিন ১/৫ কাজ। ১০জন×১০দিন×(১/৫)=২০"},
     {"q": "একটি বর্গের ক্ষেত্রফল ৬৪ বর্গমিটার। পরিসীমা কত?",
      "options": ["16m","32m","8m","64m"],
      "answer": 1, "explanation": "a²=64 → a=8m, পরিসীমা=4a=32m"},
   ]},
],
}
