# topics.py — Rony Parvej EEE Job Solution (সম্পূর্ণ সিলেবাস, ৭ দিনে ভাগ)

EEE_DAYS = [
    {
        "label": "⚡ DC Circuit (Part-1)",
        "topics": [
            "Series & Parallel Circuit — equivalent R, voltage/current divider",
            "Delta-Star Conversion — formula ও numerical",
            "Source Transformation — voltage↔current source",
            "KCL, KVL & Miscellaneous Circuit — branch current method",
            "Superposition Theorem — multi-source numerical",
            "Mesh Analysis — matrix form, supermesh",
            "Nodal Analysis — supernode সহ",
            "Thevenin's Theorem — step-by-step",
            "Norton's Theorem — Thevenin↔Norton রূপান্তর",
            "Maximum Power Transfer Theorem — proof ও numerical",
        ],
    },
    {
        "label": "🔌 AC Circuit (Part-1)",
        "topics": [
            "Sinusoid & Phasors — RMS, peak, phase angle",
            "AC Power Analysis — P, Q, S, Power Factor",
            "AC Circuit Analysis — Impedance, Admittance, series/parallel",
            "R-L-C Circuit — phasor diagram, voltage/current",
            "Resonance — series/parallel, Q-factor, Bandwidth",
            "3-Phase Analysis — star/delta, balanced load, power",
            "Wattmeter — two wattmeter method",
            "Electrostatics & Electric Fields — Coulomb, Gauss's Law",
            "Transient Analysis — RC, RL step response, time constant",
            "Filters & Frequency Response — LP/HP/BP, Bode plot",
        ],
    },
    {
        "label": "🏭 Power System (Part-2)",
        "topics": [
            "Power Factor Improvement — capacitor sizing, synchronous condenser",
            "Variable Load on Power Station — load factor, diversity factor",
            "Transmission Line — short/medium/long, ABCD parameters, Ferranti",
            "Per Unit System & Diagrams — base values, pu calculation",
            "Symmetrical Fault — 3-phase short circuit, fault MVA",
            "Unsymmetrical Fault — SLG/LL/DLG, sequence components",
            "Load Flow Study & Stability — Gauss-Seidel, swing equation",
            "Switchgear, Protection & Substation — relay types, CB rating",
            "Power Station & Thermodynamics — efficiency, heat rate, cooling",
        ],
    },
    {
        "label": "🔧 Electrical Machine (Part-3)",
        "topics": [
            "Transformer — EMF equation, OC/SC test, efficiency, regulation",
            "DC Generator — EMF equation, OCC, types, armature reaction",
            "DC Motor — back EMF, torque, speed control, starters",
            "Induction Motor — rotating field, slip, torque equation",
            "Synchronous Generator (Alternator) — EMF, voltage regulation",
            "Synchronous Motor — V-curves, hunting, starting methods",
            "Control System — Transfer function, Mason's rule, Routh stability",
        ],
    },
    {
        "label": "💡 Electronics (Part-4)",
        "topics": [
            "BJT — CB/CE/CC config, biasing, h-parameter, amplifier",
            "Operational Amplifier — inverting/non-inverting, CMRR, slew rate",
            "Diode & Semiconductor — V-I char, rectifier, Zener, filter",
            "MOSFET — enhancement/depletion, characteristics, JFET",
            "Digital Electronics — Number system, Boolean, K-map, FF, counter",
            "Power Electronics — SCR, chopper (buck/boost), inverter, PWM",
        ],
    },
    {
        "label": "📡 Communication & Signals (Part-5) — A",
        "topics": [
            "Basics of Communication — modulation types, bandwidth, noise",
            "PCM — sampling, quantization, encoding, bit rate, SNR",
            "SNR & Channel Capacity — Shannon's theorem, noise figure",
            "Amplitude Modulation (AM) — modulation index, power, BW",
            "Fourier Transform & Spectral Analysis — properties, pairs, DTFT",
            "Discrete-Time Signals & Systems — Z-transform, DFT, FFT",
        ],
    },
    {
        "label": "📶 Communication & Signals (Part-5) — B",
        "topics": [
            "Angle Modulation (FM/PM) — β, deviation, Carson's rule",
            "Digital Modulation — ASK, FSK, PSK, QAM, BER, bandwidth",
            "Signal & System — Laplace, convolution, transfer function, stability",
            "Optical Fiber Communication — types, losses, NA, applications",
            "Networking & Computing — OSI model, TCP/IP, protocols, addressing",
        ],
    },
]

# Non-Department Topics
NON_DEPT = {
    "বাংলা ভাষা ও সাহিত্য": [
        "সন্ধি — স্বর, ব্যঞ্জন, বিসর্গ সন্ধি (উদাহরণ সহ)",
        "সমাস — ৬ প্রকার, উদাহরণ ও ব্যাসবাক্য",
        "কারক ও বিভক্তি — ৬ কারক, চিহ্নিতকরণ",
        "বাংলা সাহিত্যের যুগ বিভাগ — প্রাচীন/মধ্য/আধুনিক",
        "রবীন্দ্রনাথ ঠাকুর — জীবন, রচনা, পুরস্কার",
        "কাজী নজরুল ইসলাম — জীবন ও সাহিত্যকর্ম",
        "বানান শুদ্ধি — সাধারণ ভুল বানান",
        "বাগধারা ও প্রবাদ — অর্থ ও প্রয়োগ",
        "উপসর্গ ও প্রত্যয় — বাংলা ও তৎসম",
        "বিপরীত শব্দ ও প্রতিশব্দ",
        "বাক্য শুদ্ধি — গঠনগত ভুল সংশোধন",
        "ছন্দ — মাত্রাবৃত্ত, অক্ষরবৃত্ত, স্বরবৃত্ত",
    ],
    "English Language & Literature": [
        "Tense — 12 tenses with structure & examples",
        "Voice — Active to Passive (all tenses)",
        "Narration — Direct to Indirect speech rules",
        "Preposition — common usage & tricky ones",
        "Articles — a/an/the rules & exceptions",
        "Synonym & Antonym — high-frequency words",
        "Idioms & Phrases — common expressions",
        "Sentence correction — subject-verb agreement",
        "Vocabulary — one word substitution",
        "Shakespeare — plays, characters, famous quotes",
        "Comprehension passage — reading strategy",
        "Error finding — common grammatical errors",
    ],
    "বাংলাদেশ বিষয়াবলি": [
        "মুক্তিযুদ্ধ — পটভূমি, ৭ই মার্চ, ১৬ই ডিসেম্বর",
        "সংবিধান — মূলনীতি, সংশোধনী, অনুচ্ছেদ",
        "বাংলাদেশের ভূগোল — নদ-নদী, সীমানা, বিভাগ",
        "বাংলাদেশের অর্থনীতি — GDP, রপ্তানি, রেমিট্যান্স",
        "জাতীয় বিষয় — জাতীয় প্রতীক, দিবস, পুরস্কার",
        "বাংলাদেশের ইতিহাস — ব্রিটিশ থেকে স্বাধীনতা",
        "সরকার ব্যবস্থা — সংসদ, মন্ত্রণালয়, বিচার বিভাগ",
        "বিখ্যাত ব্যক্তিত্ব — বিজ্ঞানী, সাহিত্যিক",
    ],
    "আন্তর্জাতিক বিষয়াবলি": [
        "জাতিসংঘ — গঠন, অঙ্গসংস্থা, সদর দপ্তর",
        "আন্তর্জাতিক সংগঠন — IMF, WB, WTO, WHO",
        "বিশ্বের দেশ — রাজধানী, মুদ্রা, ভাষা",
        "সাম্প্রতিক আন্তর্জাতিক ঘটনা ও চুক্তি",
        "আঞ্চলিক সংগঠন — SAARC, ASEAN, EU, AU",
        "বিশ্বযুদ্ধ — কারণ, ফলাফল",
        "নোবেল পুরস্কার — ইতিহাস ও বিজয়ী",
        "পরিবেশ চুক্তি — কিয়োটো, প্যারিস, COP",
    ],
    "সাধারণ বিজ্ঞান": [
        "পদার্থবিজ্ঞান — গতিসূত্র, কাজ-শক্তি-ক্ষমতা",
        "তাপগতিবিদ্যা — তাপমাত্রা, তাপ পরিবহন",
        "আলো — প্রতিফলন, প্রতিসরণ, লেন্স, দর্পণ",
        "শব্দ — তরঙ্গ, কম্পাঙ্ক, অতিশব্দ",
        "জীববিজ্ঞান — কোষ, DNA, বংশগতি",
        "মানবদেহ — অঙ্গতন্ত্র, রোগ-প্রতিরোধ",
        "পুষ্টি — ভিটামিন, খনিজ, অভাবজনিত রোগ",
        "দৈনন্দিন বিজ্ঞান — সাবান, গ্লাস, সিমেন্ট",
        "পরিবেশ — দূষণ, গ্রিনহাউস, ওজোন",
        "আধুনিক পদার্থবিজ্ঞান — আপেক্ষিকতা, কোয়ান্টাম",
    ],
    "কম্পিউটার ও তথ্যপ্রযুক্তি": [
        "কম্পিউটার প্রজন্ম ও শ্রেণিবিভাগ",
        "হার্ডওয়্যার — CPU, RAM, ROM, Storage",
        "অপারেটিং সিস্টেম — কাজ, প্রকার",
        "নেটওয়ার্ক — LAN/WAN, OSI 7 layer, TCP/IP",
        "ইন্টারনেট — প্রোটোকল, IP, DNS, HTTP",
        "Database — DBMS, SQL commands",
        "সাইবার নিরাপত্তা — ভাইরাস, ফায়ারওয়াল, এনক্রিপশন",
        "ই-গভর্ন্যান্স ও ডিজিটাল বাংলাদেশ",
        "প্রোগ্রামিং ধারণা — algorithm, flowchart",
        "MS Office shortcuts ও practical",
    ],
    "গাণিতিক যুক্তি": [
        "সংখ্যাতত্ত্ব — ল.সা.গু, গ.সা.গু, ভাজ্যতা",
        "শতকরা — লাভ-ক্ষতি, ছাড়, সুদ",
        "অনুপাত ও সমানুপাত",
        "বীজগণিত — সমীকরণ, উৎপাদক বিশ্লেষণ",
        "সূচক ও লগারিদম",
        "ত্রিকোণমিতি — অনুপাত, সূত্র, মান",
        "জ্যামিতি — ত্রিভুজ, বৃত্ত, চতুর্ভুজ",
        "পরিমিতি — ক্ষেত্রফল, আয়তন",
        "সম্ভাবনা — basic probability",
        "পরিসংখ্যান — গড়, মধ্যক, প্রচুরক",
        "বয়স, কাজ, সময়-দূরত্ব সমস্যা",
        "সেট তত্ত্ব — union, intersection, Venn diagram",
    ],
}

NON_DEPT_SUBJECTS = list(NON_DEPT.keys())
